-- Generated by scripts/generate-seed-sql.ts from lib/data/seed/*.ts — do not hand-edit.
-- Re-run: npx tsx scripts/generate-seed-sql.ts > supabase/seed.sql

truncate table product_facets, product_images, product_variants, products, facets restart identity cascade;

-- Facets (type / origin / use_case)
insert into facets (id, facet_type, label, slug) values ('ff453f64-ad25-4b27-ad2b-6366dcb4cc02', 'type', 'Powders', 'powders');
insert into facets (id, facet_type, label, slug) values ('a724c0df-a980-4506-b2d8-c323187cb673', 'type', 'Oils', 'oils');
insert into facets (id, facet_type, label, slug) values ('4ac0f1a0-8583-411a-8137-5217b57d8f2a', 'type', 'Whole Leaves', 'whole-leaves');
insert into facets (id, facet_type, label, slug) values ('b575b25d-aed7-4b3d-8a7f-fbd36ba84fb4', 'type', 'Roots', 'roots');
insert into facets (id, facet_type, label, slug) values ('ff7eef86-e1b3-4b23-86f2-719be2521287', 'type', 'Barks', 'barks');
insert into facets (id, facet_type, label, slug) values ('29997bc9-861b-4c59-87b2-745394ca0181', 'type', 'Seeds & Spices', 'seeds-spices');
insert into facets (id, facet_type, label, slug) values ('ffc0b626-c773-4c35-b28f-f65363057f9b', 'origin', 'Ayurvedic', 'ayurvedic');
insert into facets (id, facet_type, label, slug) values ('3701886b-55ac-4f55-824d-10a355c2189e', 'origin', 'African', 'african');
insert into facets (id, facet_type, label, slug) values ('1dc3e690-7627-4df6-94d1-6327100c11cf', 'use_case', 'Digestion & Gut Health', 'digestion-gut-health');
insert into facets (id, facet_type, label, slug) values ('c5ced096-664e-4f1e-89b3-62f86bd2b44f', 'use_case', 'Male Reproductive Health', 'male-reproductive-health');
insert into facets (id, facet_type, label, slug) values ('bea4a4ae-dd41-4078-9eff-03e60874b19b', 'use_case', 'Female Reproductive Health', 'female-reproductive-health');
insert into facets (id, facet_type, label, slug) values ('530853af-82d6-4161-93db-ef3d062e1750', 'use_case', 'Hormonal Balance', 'hormonal-balance');
insert into facets (id, facet_type, label, slug) values ('201b4c8f-0378-4a45-b5f8-6826c3b19ba0', 'use_case', 'Immune Support', 'immune-support');
insert into facets (id, facet_type, label, slug) values ('a1edd207-8462-4d84-ba2c-04e0458c9cb9', 'use_case', 'Stress & Sleep Support', 'stress-sleep-support');
insert into facets (id, facet_type, label, slug) values ('aa38ed59-489b-44f6-ab86-66d92d6118f5', 'use_case', 'Skin Care', 'skin-care');
insert into facets (id, facet_type, label, slug) values ('d0fae58b-f0d9-4448-8ea6-d7eb30e335ea', 'use_case', 'Hair Care', 'hair-care');
insert into facets (id, facet_type, label, slug) values ('f3d1200f-28a8-45f3-b3b6-8f00f8251bc7', 'use_case', 'Joint & Mobility Support', 'joint-mobility-support');
insert into facets (id, facet_type, label, slug) values ('9d4b5fa6-294f-4eac-9137-918464ae05d1', 'use_case', 'Metabolic Wellness', 'metabolic-wellness');
insert into facets (id, facet_type, label, slug) values ('49bd8950-bf58-448c-8353-adf18053a489', 'use_case', 'Heart Health', 'heart-health');
insert into facets (id, facet_type, label, slug) values ('8b721008-5f1c-42c6-ac7d-6771dc4c80bc', 'use_case', 'Blood Pressure Support', 'blood-pressure-support');
insert into facets (id, facet_type, label, slug) values ('ffb970ce-2b83-4784-96ea-29604e69f1d5', 'use_case', 'Memory & Focus', 'memory-focus');

-- Cayenne Pepper
insert into products (id, name, slug, description, status, is_pet_safe, pet_safe_note) values ('c0b2193d-aaa3-4c0f-865f-7ada6fe68208', 'Cayenne Pepper', 'cayenne-pepper', 'Ground from sun-ripened cayenne pods, this fiery red powder is a kitchen staple across West African cooking and a traditional pick for warming, circulation-supporting blends. Stir a pinch into teas, soups, or tonics. Traditionally used to support healthy circulation and metabolism as part of a balanced diet.', 'published', false, null);
insert into product_variants (id, product_id, size_label, price, currency, stock_quantity, low_stock_threshold, subscription_eligible, sku) values ('5451f23d-5057-43a0-83ca-e33960c8addd', 'c0b2193d-aaa3-4c0f-865f-7ada6fe68208', '100g', 3500, 'NGN', 42, 10, false, 'SO-CAY-100');
insert into product_variants (id, product_id, size_label, price, currency, stock_quantity, low_stock_threshold, subscription_eligible, sku) values ('1b5a806e-a0f6-4341-b4e5-63fc2d1ad3c8', 'c0b2193d-aaa3-4c0f-865f-7ada6fe68208', '250g', 7500, 'NGN', 18, 10, false, 'SO-CAY-250');
insert into product_variants (id, product_id, size_label, price, currency, stock_quantity, low_stock_threshold, subscription_eligible, sku) values ('f990994a-bae3-48b2-b0b1-be1b0b0b3839', 'c0b2193d-aaa3-4c0f-865f-7ada6fe68208', '500g', 13500, 'NGN', 6, 10, false, 'SO-CAY-500');
insert into product_variants (id, product_id, size_label, price, currency, stock_quantity, low_stock_threshold, subscription_eligible, sku) values ('3c4c38ce-a4fd-401d-84c2-5aa91db0abc9', 'c0b2193d-aaa3-4c0f-865f-7ada6fe68208', '1kg', 24000, 'NGN', 0, 10, false, 'SO-CAY-1000');
insert into product_images (id, product_id, storage_path, alt_text, sort_order) values ('e8a52c2c-fab3-4ed6-b042-501d5fc93aaf', 'c0b2193d-aaa3-4c0f-865f-7ada6fe68208', '/images/products/cayenne-pepper.jpeg', 'Sofa Organics Cayenne Pepper kraft pouch beside a bowl of ground cayenne and fresh chillies', 0);
insert into product_facets (product_id, facet_id) values ('c0b2193d-aaa3-4c0f-865f-7ada6fe68208', 'ff453f64-ad25-4b27-ad2b-6366dcb4cc02');
insert into product_facets (product_id, facet_id) values ('c0b2193d-aaa3-4c0f-865f-7ada6fe68208', '3701886b-55ac-4f55-824d-10a355c2189e');
insert into product_facets (product_id, facet_id) values ('c0b2193d-aaa3-4c0f-865f-7ada6fe68208', '9d4b5fa6-294f-4eac-9137-918464ae05d1');
insert into product_facets (product_id, facet_id) values ('c0b2193d-aaa3-4c0f-865f-7ada6fe68208', '49bd8950-bf58-448c-8353-adf18053a489');
insert into product_facets (product_id, facet_id) values ('c0b2193d-aaa3-4c0f-865f-7ada6fe68208', '1dc3e690-7627-4df6-94d1-6327100c11cf');

-- Chia Seeds
insert into products (id, name, slug, description, status, is_pet_safe, pet_safe_note) values ('6113d790-a142-439c-8cc5-531323bcb2ea', 'Chia Seeds', 'chia-seeds', 'Whole, unroasted chia seeds with their natural mottled black-and-white color intact. Soak into puddings, stir into smoothies, or fold into baking. Traditionally used to support digestion and heart health, thanks to their fibre and natural mucilage. A small amount is also a common addition to pet meals; see the pet-safe notes below for guidance.', 'published', true, 'A teaspoon of soaked (never dry) chia seeds is a common addition to a dog''s meal for fibre. Introduce it gradually and always soak the seeds first, since dry seeds can swell in the throat. Check with your vet first for cats or animals with existing conditions.');
insert into product_variants (id, product_id, size_label, price, currency, stock_quantity, low_stock_threshold, subscription_eligible, sku) values ('52d8fc7d-92b6-4193-bc99-3ff73f5bfab9', '6113d790-a142-439c-8cc5-531323bcb2ea', '100g', 2800, 'NGN', 55, 10, false, 'SO-CHI-100');
insert into product_variants (id, product_id, size_label, price, currency, stock_quantity, low_stock_threshold, subscription_eligible, sku) values ('226da50b-b93d-46fa-aca4-8cb74b32eb34', '6113d790-a142-439c-8cc5-531323bcb2ea', '250g', 6000, 'NGN', 30, 10, false, 'SO-CHI-250');
insert into product_variants (id, product_id, size_label, price, currency, stock_quantity, low_stock_threshold, subscription_eligible, sku) values ('b601abf6-bd27-4caa-a114-3ed07fd9c3ae', '6113d790-a142-439c-8cc5-531323bcb2ea', '500g', 10500, 'NGN', 12, 10, false, 'SO-CHI-500');
insert into product_variants (id, product_id, size_label, price, currency, stock_quantity, low_stock_threshold, subscription_eligible, sku) values ('41c04e74-e259-4415-a71d-0adb53fa69be', '6113d790-a142-439c-8cc5-531323bcb2ea', '1kg', 19000, 'NGN', 8, 10, false, 'SO-CHI-1000');
insert into product_images (id, product_id, storage_path, alt_text, sort_order) values ('462f509d-7c34-4cd8-aaa6-f8ced22e8472', '6113d790-a142-439c-8cc5-531323bcb2ea', '/images/products/chia-seeds.jpeg', 'Sofa Organics Chia Seeds kraft pouch showing the whole seeds through the window', 0);
insert into product_facets (product_id, facet_id) values ('6113d790-a142-439c-8cc5-531323bcb2ea', '29997bc9-861b-4c59-87b2-745394ca0181');
insert into product_facets (product_id, facet_id) values ('6113d790-a142-439c-8cc5-531323bcb2ea', '3701886b-55ac-4f55-824d-10a355c2189e');
insert into product_facets (product_id, facet_id) values ('6113d790-a142-439c-8cc5-531323bcb2ea', '1dc3e690-7627-4df6-94d1-6327100c11cf');
insert into product_facets (product_id, facet_id) values ('6113d790-a142-439c-8cc5-531323bcb2ea', '49bd8950-bf58-448c-8353-adf18053a489');
insert into product_facets (product_id, facet_id) values ('6113d790-a142-439c-8cc5-531323bcb2ea', '9d4b5fa6-294f-4eac-9137-918464ae05d1');

-- Gingko Leaves
insert into products (id, name, slug, description, status, is_pet_safe, pet_safe_note) values ('ecb4ca90-3d0a-46b1-800b-299eb7cb77b2', 'Gingko Leaves', 'gingko-leaves', 'Dried, hand-cut gingko biloba leaves for steeping into tea or preparing your own tincture. One of the oldest botanicals in traditional practice, gingko is often used to support focus and mental clarity. Steep 1 to 2 teaspoons in hot water for 8 to 10 minutes.', 'published', false, null);
insert into product_variants (id, product_id, size_label, price, currency, stock_quantity, low_stock_threshold, subscription_eligible, sku) values ('42527427-d368-4f2f-b014-a772aa62ce12', 'ecb4ca90-3d0a-46b1-800b-299eb7cb77b2', '100g', 4200, 'NGN', 38, 10, false, 'SO-GIN-100');
insert into product_variants (id, product_id, size_label, price, currency, stock_quantity, low_stock_threshold, subscription_eligible, sku) values ('fffa48ba-a527-471d-aa45-6040615a3903', 'ecb4ca90-3d0a-46b1-800b-299eb7cb77b2', '250g', 9000, 'NGN', 14, 10, false, 'SO-GIN-250');
insert into product_variants (id, product_id, size_label, price, currency, stock_quantity, low_stock_threshold, subscription_eligible, sku) values ('8bd6719f-c01c-4254-9a41-35e39e05b894', 'ecb4ca90-3d0a-46b1-800b-299eb7cb77b2', '500g', 16000, 'NGN', 4, 10, false, 'SO-GIN-500');
insert into product_images (id, product_id, storage_path, alt_text, sort_order) values ('1d9fff37-3e8d-4e9d-a242-ce46c3516fc3', 'ecb4ca90-3d0a-46b1-800b-299eb7cb77b2', '/images/products/gingko-leaves.jpeg', 'Sofa Organics Gingko Leaves kraft pouch beside a bowl of dried leaves, a wooden spoon, and a dropper bottle', 0);
insert into product_facets (product_id, facet_id) values ('ecb4ca90-3d0a-46b1-800b-299eb7cb77b2', '4ac0f1a0-8583-411a-8137-5217b57d8f2a');
insert into product_facets (product_id, facet_id) values ('ecb4ca90-3d0a-46b1-800b-299eb7cb77b2', 'ffc0b626-c773-4c35-b28f-f65363057f9b');
insert into product_facets (product_id, facet_id) values ('ecb4ca90-3d0a-46b1-800b-299eb7cb77b2', 'ffb970ce-2b83-4784-96ea-29604e69f1d5');

-- Moringa Root Extract Powder
insert into products (id, name, slug, description, status, is_pet_safe, pet_safe_note) values ('2f634719-320d-4161-93bd-0dd4801951bb', 'Moringa Root Extract Powder', 'moringa-root-extract-powder', 'A concentrated extract powder milled from moringa root, a plant long relied on across West African herbal practice. Mix a small measure into water or juice. Traditionally used to support the body''s natural defenses and everyday vitality. Start with a small amount to see how it suits you.', 'published', false, null);
insert into product_variants (id, product_id, size_label, price, currency, stock_quantity, low_stock_threshold, subscription_eligible, sku) values ('b6d2fb1a-ab28-48fd-9982-d0f0153e20ac', '2f634719-320d-4161-93bd-0dd4801951bb', '100g', 4800, 'NGN', 26, 10, false, 'SO-MOR-100');
insert into product_variants (id, product_id, size_label, price, currency, stock_quantity, low_stock_threshold, subscription_eligible, sku) values ('efd34a69-ba54-433f-a193-ad3dd4bfc701', '2f634719-320d-4161-93bd-0dd4801951bb', '250g', 10500, 'NGN', 9, 10, false, 'SO-MOR-250');
insert into product_variants (id, product_id, size_label, price, currency, stock_quantity, low_stock_threshold, subscription_eligible, sku) values ('0b05854b-475b-4e0a-b241-026bf49a9d09', '2f634719-320d-4161-93bd-0dd4801951bb', '500g', 19000, 'NGN', 0, 10, false, 'SO-MOR-500');
insert into product_images (id, product_id, storage_path, alt_text, sort_order) values ('8137d0cf-c44f-4e98-9cd4-e678f0db2b62', '2f634719-320d-4161-93bd-0dd4801951bb', '/images/products/moringa-root-extract-powder.jpeg', 'Sofa Organics Moringa Root Extract Powder kraft pouch showing the fine tan powder through the window', 0);
insert into product_facets (product_id, facet_id) values ('2f634719-320d-4161-93bd-0dd4801951bb', 'ff453f64-ad25-4b27-ad2b-6366dcb4cc02');
insert into product_facets (product_id, facet_id) values ('2f634719-320d-4161-93bd-0dd4801951bb', '3701886b-55ac-4f55-824d-10a355c2189e');
insert into product_facets (product_id, facet_id) values ('2f634719-320d-4161-93bd-0dd4801951bb', '201b4c8f-0378-4a45-b5f8-6826c3b19ba0');
insert into product_facets (product_id, facet_id) values ('2f634719-320d-4161-93bd-0dd4801951bb', 'c5ced096-664e-4f1e-89b3-62f86bd2b44f');

-- Hexane-Free Castor Oil
insert into products (id, name, slug, description, status, is_pet_safe, pet_safe_note) values ('a4391267-c669-4d6f-a458-6ecd6612f9b4', 'Hexane-Free Castor Oil', 'hexane-free-castor-oil', 'Cold-pressed and hexane-free, this thick, pale-gold castor oil is a scalp and skin staple across both African and Ayurvedic beauty traditions. Warm a small amount between your palms before massaging into hair ends or dry skin.', 'published', false, null);
insert into product_variants (id, product_id, size_label, price, currency, stock_quantity, low_stock_threshold, subscription_eligible, sku) values ('3a42f8c2-6d1a-4cbb-8358-e54bf270415f', 'a4391267-c669-4d6f-a458-6ecd6612f9b4', '100ml', 5200, 'NGN', 33, 10, false, 'SO-CAS-100');
insert into product_variants (id, product_id, size_label, price, currency, stock_quantity, low_stock_threshold, subscription_eligible, sku) values ('d3b3a152-15c2-4bb6-8d99-0ae66a4a07a3', 'a4391267-c669-4d6f-a458-6ecd6612f9b4', '250ml', 11000, 'NGN', 20, 10, false, 'SO-CAS-250');
insert into product_variants (id, product_id, size_label, price, currency, stock_quantity, low_stock_threshold, subscription_eligible, sku) values ('802916d8-03d6-49b9-98b9-6e4ae8fcada6', 'a4391267-c669-4d6f-a458-6ecd6612f9b4', '500ml', 19500, 'NGN', 7, 10, false, 'SO-CAS-500');
insert into product_facets (product_id, facet_id) values ('a4391267-c669-4d6f-a458-6ecd6612f9b4', 'a724c0df-a980-4506-b2d8-c323187cb673');
insert into product_facets (product_id, facet_id) values ('a4391267-c669-4d6f-a458-6ecd6612f9b4', 'ffc0b626-c773-4c35-b28f-f65363057f9b');
insert into product_facets (product_id, facet_id) values ('a4391267-c669-4d6f-a458-6ecd6612f9b4', 'd0fae58b-f0d9-4448-8ea6-d7eb30e335ea');
insert into product_facets (product_id, facet_id) values ('a4391267-c669-4d6f-a458-6ecd6612f9b4', 'aa38ed59-489b-44f6-ab86-66d92d6118f5');

-- Triphala Powder
insert into products (id, name, slug, description, status, is_pet_safe, pet_safe_note) values ('2cc5bbaf-cb62-42b5-a493-1442ca572f4e', 'Triphala Powder', 'triphala-powder', 'A traditional Ayurvedic blend of three dried fruits (amla, bibhitaki, and haritaki), ground fine. Stirred into warm water, it''s one of the most common everyday picks for digestive support in Ayurvedic practice.', 'published', false, null);
insert into product_variants (id, product_id, size_label, price, currency, stock_quantity, low_stock_threshold, subscription_eligible, sku) values ('4ecfbb72-2994-4a46-b7a8-0909b4c2d69a', '2cc5bbaf-cb62-42b5-a493-1442ca572f4e', '100g', 3200, 'NGN', 40, 10, false, 'SO-TRI-100');
insert into product_variants (id, product_id, size_label, price, currency, stock_quantity, low_stock_threshold, subscription_eligible, sku) values ('b8000059-efa3-4c89-a2f1-ee7788cc0a5a', '2cc5bbaf-cb62-42b5-a493-1442ca572f4e', '250g', 7000, 'NGN', 22, 10, false, 'SO-TRI-250');
insert into product_variants (id, product_id, size_label, price, currency, stock_quantity, low_stock_threshold, subscription_eligible, sku) values ('43387ca7-eac2-4b48-bf6f-e354cdc6c7f7', '2cc5bbaf-cb62-42b5-a493-1442ca572f4e', '500g', 12500, 'NGN', 10, 10, false, 'SO-TRI-500');
insert into product_facets (product_id, facet_id) values ('2cc5bbaf-cb62-42b5-a493-1442ca572f4e', 'ff453f64-ad25-4b27-ad2b-6366dcb4cc02');
insert into product_facets (product_id, facet_id) values ('2cc5bbaf-cb62-42b5-a493-1442ca572f4e', 'ffc0b626-c773-4c35-b28f-f65363057f9b');
insert into product_facets (product_id, facet_id) values ('2cc5bbaf-cb62-42b5-a493-1442ca572f4e', '1dc3e690-7627-4df6-94d1-6327100c11cf');

-- Ashwagandha Root
insert into products (id, name, slug, description, status, is_pet_safe, pet_safe_note) values ('52572da1-687c-4f16-909b-42129de18ace', 'Ashwagandha Root', 'ashwagandha-root', 'Whole, dried ashwagandha root pieces for simmering into a traditional decoction. A cornerstone of Ayurvedic practice, it''s commonly worked into evening routines to support a steadier response to stress and better sleep.', 'published', false, null);
insert into product_variants (id, product_id, size_label, price, currency, stock_quantity, low_stock_threshold, subscription_eligible, sku) values ('62eb944f-e875-45c8-bc4f-f3d6de037780', '52572da1-687c-4f16-909b-42129de18ace', '100g', 3800, 'NGN', 29, 10, false, 'SO-ASH-100');
insert into product_variants (id, product_id, size_label, price, currency, stock_quantity, low_stock_threshold, subscription_eligible, sku) values ('ff5013dc-b4ec-4686-a894-9c8b42da46a2', '52572da1-687c-4f16-909b-42129de18ace', '250g', 8200, 'NGN', 11, 10, false, 'SO-ASH-250');
insert into product_variants (id, product_id, size_label, price, currency, stock_quantity, low_stock_threshold, subscription_eligible, sku) values ('09125964-2ebe-4237-94ae-ea4d6c496cf6', '52572da1-687c-4f16-909b-42129de18ace', '500g', 15000, 'NGN', 0, 10, false, 'SO-ASH-500');
insert into product_facets (product_id, facet_id) values ('52572da1-687c-4f16-909b-42129de18ace', 'b575b25d-aed7-4b3d-8a7f-fbd36ba84fb4');
insert into product_facets (product_id, facet_id) values ('52572da1-687c-4f16-909b-42129de18ace', 'ffc0b626-c773-4c35-b28f-f65363057f9b');
insert into product_facets (product_id, facet_id) values ('52572da1-687c-4f16-909b-42129de18ace', 'a1edd207-8462-4d84-ba2c-04e0458c9cb9');
insert into product_facets (product_id, facet_id) values ('52572da1-687c-4f16-909b-42129de18ace', '530853af-82d6-4161-93db-ef3d062e1750');

-- Manjakani (Oak Galls)
insert into products (id, name, slug, description, status, is_pet_safe, pet_safe_note) values ('5b88d6c6-fa3a-44fa-af68-472db3f46fe9', 'Manjakani (Oak Galls)', 'manjakani-oak-galls', 'Dried oak galls, ground to a fine powder, drawn from a women''s wellness tradition practiced across South and Southeast Asia. Traditionally prepared as a wash as part of postpartum and everyday feminine care routines.', 'published', false, null);
insert into product_variants (id, product_id, size_label, price, currency, stock_quantity, low_stock_threshold, subscription_eligible, sku) values ('14de5513-ad3c-475d-a28b-6b6b84f727bb', '5b88d6c6-fa3a-44fa-af68-472db3f46fe9', '100g', 6500, 'NGN', 17, 10, false, 'SO-MAN-100');
insert into product_variants (id, product_id, size_label, price, currency, stock_quantity, low_stock_threshold, subscription_eligible, sku) values ('caaa03c9-a70d-40e3-8981-d3b03aeee043', '5b88d6c6-fa3a-44fa-af68-472db3f46fe9', '250g', 14000, 'NGN', 5, 10, false, 'SO-MAN-250');
insert into product_facets (product_id, facet_id) values ('5b88d6c6-fa3a-44fa-af68-472db3f46fe9', 'ff453f64-ad25-4b27-ad2b-6366dcb4cc02');
insert into product_facets (product_id, facet_id) values ('5b88d6c6-fa3a-44fa-af68-472db3f46fe9', 'ffc0b626-c773-4c35-b28f-f65363057f9b');
insert into product_facets (product_id, facet_id) values ('5b88d6c6-fa3a-44fa-af68-472db3f46fe9', 'bea4a4ae-dd41-4078-9eff-03e60874b19b');
insert into product_facets (product_id, facet_id) values ('5b88d6c6-fa3a-44fa-af68-472db3f46fe9', 'aa38ed59-489b-44f6-ab86-66d92d6118f5');

-- Olive Leaves
insert into products (id, name, slug, description, status, is_pet_safe, pet_safe_note) values ('680bbbc8-5802-4eaa-9ca6-abaeeeaffd9b', 'Olive Leaves', 'olive-leaves', 'Whole, air-dried olive leaves for a mild, herbaceous infusion. Part of Mediterranean and African herbal tradition alike, olive leaf tea has long been a daily habit for supporting immune function and heart health.', 'published', false, null);
insert into product_variants (id, product_id, size_label, price, currency, stock_quantity, low_stock_threshold, subscription_eligible, sku) values ('73408d7d-2e28-4c90-b822-ea83a9af0d32', '680bbbc8-5802-4eaa-9ca6-abaeeeaffd9b', '100g', 3000, 'NGN', 48, 10, false, 'SO-OLV-100');
insert into product_variants (id, product_id, size_label, price, currency, stock_quantity, low_stock_threshold, subscription_eligible, sku) values ('eab3e22d-9ca0-4133-a4ad-3df0ed1c6492', '680bbbc8-5802-4eaa-9ca6-abaeeeaffd9b', '250g', 6500, 'NGN', 26, 10, false, 'SO-OLV-250');
insert into product_variants (id, product_id, size_label, price, currency, stock_quantity, low_stock_threshold, subscription_eligible, sku) values ('1bc33675-d01c-452c-9c24-852cd57d1718', '680bbbc8-5802-4eaa-9ca6-abaeeeaffd9b', '500g', 11500, 'NGN', 9, 10, false, 'SO-OLV-500');
insert into product_facets (product_id, facet_id) values ('680bbbc8-5802-4eaa-9ca6-abaeeeaffd9b', '4ac0f1a0-8583-411a-8137-5217b57d8f2a');
insert into product_facets (product_id, facet_id) values ('680bbbc8-5802-4eaa-9ca6-abaeeeaffd9b', '3701886b-55ac-4f55-824d-10a355c2189e');
insert into product_facets (product_id, facet_id) values ('680bbbc8-5802-4eaa-9ca6-abaeeeaffd9b', '201b4c8f-0378-4a45-b5f8-6826c3b19ba0');
insert into product_facets (product_id, facet_id) values ('680bbbc8-5802-4eaa-9ca6-abaeeeaffd9b', '49bd8950-bf58-448c-8353-adf18053a489');
insert into product_facets (product_id, facet_id) values ('680bbbc8-5802-4eaa-9ca6-abaeeeaffd9b', '8b721008-5f1c-42c6-ac7d-6771dc4c80bc');

-- Wormwood
insert into products (id, name, slug, description, status, is_pet_safe, pet_safe_note) values ('8085d4d7-97cf-46c1-b87d-29c4be602273', 'Wormwood', 'wormwood', 'Dried wormwood leaf and stem, cut for steeping into a traditional bitter infusion. Long used across African herbal practice to ease digestive discomfort. Its flavor is intensely bitter by design, so start with a short steep.', 'published', false, null);
insert into product_variants (id, product_id, size_label, price, currency, stock_quantity, low_stock_threshold, subscription_eligible, sku) values ('e4d67245-7f16-40ed-a1ec-6154221871e4', '8085d4d7-97cf-46c1-b87d-29c4be602273', '100g', 3400, 'NGN', 31, 10, false, 'SO-WRM-100');
insert into product_variants (id, product_id, size_label, price, currency, stock_quantity, low_stock_threshold, subscription_eligible, sku) values ('31805388-5c29-4c10-8cf4-37fcd8fe491d', '8085d4d7-97cf-46c1-b87d-29c4be602273', '250g', 7200, 'NGN', 15, 10, false, 'SO-WRM-250');
insert into product_facets (product_id, facet_id) values ('8085d4d7-97cf-46c1-b87d-29c4be602273', '4ac0f1a0-8583-411a-8137-5217b57d8f2a');
insert into product_facets (product_id, facet_id) values ('8085d4d7-97cf-46c1-b87d-29c4be602273', '3701886b-55ac-4f55-824d-10a355c2189e');
insert into product_facets (product_id, facet_id) values ('8085d4d7-97cf-46c1-b87d-29c4be602273', '1dc3e690-7627-4df6-94d1-6327100c11cf');

-- Black Walnut Hull
insert into products (id, name, slug, description, status, is_pet_safe, pet_safe_note) values ('b234a767-35c8-485c-ab99-75ec6f7787ed', 'Black Walnut Hull', 'black-walnut-hull', 'Dried, cracked black walnut hull for simmering into a traditional decoction. A longstanding staple of African herbal practice, used to support digestion and clearer-looking skin.', 'published', false, null);
insert into product_variants (id, product_id, size_label, price, currency, stock_quantity, low_stock_threshold, subscription_eligible, sku) values ('1909c043-ea0f-4544-b9d4-0071204390c8', 'b234a767-35c8-485c-ab99-75ec6f7787ed', '100g', 3600, 'NGN', 24, 10, false, 'SO-BWH-100');
insert into product_variants (id, product_id, size_label, price, currency, stock_quantity, low_stock_threshold, subscription_eligible, sku) values ('6d60a36e-e769-45f8-b4b9-76323e6c6746', 'b234a767-35c8-485c-ab99-75ec6f7787ed', '250g', 7800, 'NGN', 8, 10, false, 'SO-BWH-250');
insert into product_facets (product_id, facet_id) values ('b234a767-35c8-485c-ab99-75ec6f7787ed', 'ff7eef86-e1b3-4b23-86f2-719be2521287');
insert into product_facets (product_id, facet_id) values ('b234a767-35c8-485c-ab99-75ec6f7787ed', '3701886b-55ac-4f55-824d-10a355c2189e');
insert into product_facets (product_id, facet_id) values ('b234a767-35c8-485c-ab99-75ec6f7787ed', '1dc3e690-7627-4df6-94d1-6327100c11cf');
insert into product_facets (product_id, facet_id) values ('b234a767-35c8-485c-ab99-75ec6f7787ed', 'aa38ed59-489b-44f6-ab86-66d92d6118f5');

-- Whole Cloves
insert into products (id, name, slug, description, status, is_pet_safe, pet_safe_note) values ('47a8093c-635a-4696-80d7-5f0ff5e9b28f', 'Whole Cloves', 'whole-cloves', 'Sun-dried whole clove buds with their deep, warming aroma intact. Just as at home in the kitchen as in a wellness routine. Simmer a few into tea, or grind fresh as needed for the fullest flavor.', 'published', false, null);
insert into product_variants (id, product_id, size_label, price, currency, stock_quantity, low_stock_threshold, subscription_eligible, sku) values ('44533368-c80e-4bad-a957-354fb9d4e2e6', '47a8093c-635a-4696-80d7-5f0ff5e9b28f', '100g', 2600, 'NGN', 60, 10, false, 'SO-CLV-100');
insert into product_variants (id, product_id, size_label, price, currency, stock_quantity, low_stock_threshold, subscription_eligible, sku) values ('1321a9e1-ac81-4a39-8e03-4bc9c42fdb43', '47a8093c-635a-4696-80d7-5f0ff5e9b28f', '250g', 5600, 'NGN', 34, 10, false, 'SO-CLV-250');
insert into product_variants (id, product_id, size_label, price, currency, stock_quantity, low_stock_threshold, subscription_eligible, sku) values ('815dafe1-8b89-4172-9b64-a5bc4fc34602', '47a8093c-635a-4696-80d7-5f0ff5e9b28f', '500g', 10000, 'NGN', 19, 10, false, 'SO-CLV-500');
insert into product_facets (product_id, facet_id) values ('47a8093c-635a-4696-80d7-5f0ff5e9b28f', '29997bc9-861b-4c59-87b2-745394ca0181');
insert into product_facets (product_id, facet_id) values ('47a8093c-635a-4696-80d7-5f0ff5e9b28f', '3701886b-55ac-4f55-824d-10a355c2189e');
insert into product_facets (product_id, facet_id) values ('47a8093c-635a-4696-80d7-5f0ff5e9b28f', '1dc3e690-7627-4df6-94d1-6327100c11cf');
insert into product_facets (product_id, facet_id) values ('47a8093c-635a-4696-80d7-5f0ff5e9b28f', '201b4c8f-0378-4a45-b5f8-6826c3b19ba0');

-- Avocado Oil
insert into products (id, name, slug, description, status, is_pet_safe, pet_safe_note) values ('49dca759-6938-4a3a-8b7f-79834712492c', 'Avocado Oil', 'avocado-oil', 'Cold-pressed, deep-green avocado oil, rich and fast-absorbing. A West African beauty-routine staple for softening dry skin and taming stubborn hair ends.', 'published', false, null);
insert into product_variants (id, product_id, size_label, price, currency, stock_quantity, low_stock_threshold, subscription_eligible, sku) values ('b1a5606a-3d30-45e7-8935-c6eea72f9471', '49dca759-6938-4a3a-8b7f-79834712492c', '100ml', 4600, 'NGN', 27, 10, false, 'SO-AVO-100');
insert into product_variants (id, product_id, size_label, price, currency, stock_quantity, low_stock_threshold, subscription_eligible, sku) values ('2dc369ee-99bc-41da-8eb0-b1209e8df735', '49dca759-6938-4a3a-8b7f-79834712492c', '250ml', 9800, 'NGN', 12, 10, false, 'SO-AVO-250');
insert into product_facets (product_id, facet_id) values ('49dca759-6938-4a3a-8b7f-79834712492c', 'a724c0df-a980-4506-b2d8-c323187cb673');
insert into product_facets (product_id, facet_id) values ('49dca759-6938-4a3a-8b7f-79834712492c', '3701886b-55ac-4f55-824d-10a355c2189e');
insert into product_facets (product_id, facet_id) values ('49dca759-6938-4a3a-8b7f-79834712492c', 'aa38ed59-489b-44f6-ab86-66d92d6118f5');
insert into product_facets (product_id, facet_id) values ('49dca759-6938-4a3a-8b7f-79834712492c', 'd0fae58b-f0d9-4448-8ea6-d7eb30e335ea');

-- Jojoba Oil
insert into products (id, name, slug, description, status, is_pet_safe, pet_safe_note) values ('316cac31-a4d1-41ac-b5b4-6bb48c0031df', 'Jojoba Oil', 'jojoba-oil', 'Light, close-to-skin''s-own jojoba oil that absorbs without a greasy finish. A gentle daily pick for face, body, and scalp, and a common base oil in homemade pet paw and nose balms.', 'published', true, 'A widely used base oil in DIY paw-balm recipes thanks to its gentle, non-greasy profile. Use a light layer and keep it away from your pet''s eyes.');
insert into product_variants (id, product_id, size_label, price, currency, stock_quantity, low_stock_threshold, subscription_eligible, sku) values ('2f67e00c-0b94-4c21-be58-1628fb2608af', '316cac31-a4d1-41ac-b5b4-6bb48c0031df', '100ml', 5000, 'NGN', 21, 10, false, 'SO-JOJ-100');
insert into product_variants (id, product_id, size_label, price, currency, stock_quantity, low_stock_threshold, subscription_eligible, sku) values ('a6a362f9-2139-42af-ba66-bcca2ba5b4dc', '316cac31-a4d1-41ac-b5b4-6bb48c0031df', '250ml', 10800, 'NGN', 3, 10, false, 'SO-JOJ-250');
insert into product_facets (product_id, facet_id) values ('316cac31-a4d1-41ac-b5b4-6bb48c0031df', 'a724c0df-a980-4506-b2d8-c323187cb673');
insert into product_facets (product_id, facet_id) values ('316cac31-a4d1-41ac-b5b4-6bb48c0031df', '3701886b-55ac-4f55-824d-10a355c2189e');
insert into product_facets (product_id, facet_id) values ('316cac31-a4d1-41ac-b5b4-6bb48c0031df', 'aa38ed59-489b-44f6-ab86-66d92d6118f5');
insert into product_facets (product_id, facet_id) values ('316cac31-a4d1-41ac-b5b4-6bb48c0031df', 'd0fae58b-f0d9-4448-8ea6-d7eb30e335ea');

-- Coconut Oil
insert into products (id, name, slug, description, status, is_pet_safe, pet_safe_note) values ('e160a94c-5b52-4ba7-b9ee-302e0767e011', 'Coconut Oil', 'coconut-oil', 'Unrefined, cold-pressed coconut oil that goes solid below room temperature and melts on contact with skin. A do-everything staple for cooking, hair, and skin routines alike.', 'published', true, 'A small, occasional spoonful is a common treat addition for dogs. Introduce gradually and check with your vet first if your pet has a sensitive stomach.');
insert into product_variants (id, product_id, size_label, price, currency, stock_quantity, low_stock_threshold, subscription_eligible, sku) values ('8cf5d105-742e-44f7-9fe5-0a00490ff793', 'e160a94c-5b52-4ba7-b9ee-302e0767e011', '250g', 4200, 'NGN', 44, 10, false, 'SO-COC-250');
insert into product_variants (id, product_id, size_label, price, currency, stock_quantity, low_stock_threshold, subscription_eligible, sku) values ('2552908a-ac2f-4669-ab78-044207d79041', 'e160a94c-5b52-4ba7-b9ee-302e0767e011', '500g', 7800, 'NGN', 25, 10, false, 'SO-COC-500');
insert into product_variants (id, product_id, size_label, price, currency, stock_quantity, low_stock_threshold, subscription_eligible, sku) values ('5995510b-1e07-4732-baec-00aaaba4d0b8', 'e160a94c-5b52-4ba7-b9ee-302e0767e011', '1kg', 14000, 'NGN', 13, 10, false, 'SO-COC-1000');
insert into product_facets (product_id, facet_id) values ('e160a94c-5b52-4ba7-b9ee-302e0767e011', 'a724c0df-a980-4506-b2d8-c323187cb673');
insert into product_facets (product_id, facet_id) values ('e160a94c-5b52-4ba7-b9ee-302e0767e011', '3701886b-55ac-4f55-824d-10a355c2189e');
insert into product_facets (product_id, facet_id) values ('e160a94c-5b52-4ba7-b9ee-302e0767e011', 'd0fae58b-f0d9-4448-8ea6-d7eb30e335ea');
insert into product_facets (product_id, facet_id) values ('e160a94c-5b52-4ba7-b9ee-302e0767e011', 'aa38ed59-489b-44f6-ab86-66d92d6118f5');

-- Raw Shea Butter
insert into products (id, name, slug, description, status, is_pet_safe, pet_safe_note) values ('207bb778-0abf-43f0-9776-308d8d2e2cc6', 'Raw Shea Butter', 'raw-shea-butter', 'Unrefined, ivory-toned shea butter, hand-whipped from shea nuts in the West African tradition it''s named for. Rich and deeply moisturizing. Scoop a small amount and warm it between your palms before applying.', 'published', true, 'Raw shea butter is a common ingredient in homemade paw-balm recipes. Apply a thin layer and monitor to make sure your pet doesn''t lick it off immediately.');
insert into product_variants (id, product_id, size_label, price, currency, stock_quantity, low_stock_threshold, subscription_eligible, sku) values ('5b9575bf-8ca8-480e-b1b5-64628801e384', '207bb778-0abf-43f0-9776-308d8d2e2cc6', '100g', 3000, 'NGN', 52, 10, false, 'SO-SHE-100');
insert into product_variants (id, product_id, size_label, price, currency, stock_quantity, low_stock_threshold, subscription_eligible, sku) values ('af24d9c2-42fc-4dc1-8ed3-5700942379fa', '207bb778-0abf-43f0-9776-308d8d2e2cc6', '250g', 6500, 'NGN', 28, 10, false, 'SO-SHE-250');
insert into product_variants (id, product_id, size_label, price, currency, stock_quantity, low_stock_threshold, subscription_eligible, sku) values ('e54a34e3-1b62-43a4-b152-8c21bfbe86e9', '207bb778-0abf-43f0-9776-308d8d2e2cc6', '500g', 11500, 'NGN', 6, 10, false, 'SO-SHE-500');
insert into product_facets (product_id, facet_id) values ('207bb778-0abf-43f0-9776-308d8d2e2cc6', 'a724c0df-a980-4506-b2d8-c323187cb673');
insert into product_facets (product_id, facet_id) values ('207bb778-0abf-43f0-9776-308d8d2e2cc6', '3701886b-55ac-4f55-824d-10a355c2189e');
insert into product_facets (product_id, facet_id) values ('207bb778-0abf-43f0-9776-308d8d2e2cc6', 'aa38ed59-489b-44f6-ab86-66d92d6118f5');
insert into product_facets (product_id, facet_id) values ('207bb778-0abf-43f0-9776-308d8d2e2cc6', 'd0fae58b-f0d9-4448-8ea6-d7eb30e335ea');
insert into product_facets (product_id, facet_id) values ('207bb778-0abf-43f0-9776-308d8d2e2cc6', 'f3d1200f-28a8-45f3-b3b6-8f00f8251bc7');

-- Frankincense Oil
insert into products (id, name, slug, description, status, is_pet_safe, pet_safe_note) values ('c0da4df3-7de8-4a85-84bd-aefb5a556fae', 'Frankincense Oil', 'frankincense-oil', 'Steam-distilled frankincense oil from resin tapped in the Horn of Africa tradition. Warm, resinous, and grounding. A drop or two blended into a carrier oil suits an evening wind-down or a post-workout massage equally well.', 'published', false, null);
insert into product_variants (id, product_id, size_label, price, currency, stock_quantity, low_stock_threshold, subscription_eligible, sku) values ('e19bf614-3ee5-4487-a5d6-e429c292a19b', 'c0da4df3-7de8-4a85-84bd-aefb5a556fae', '30ml', 8500, 'NGN', 19, 10, false, 'SO-FRA-30');
insert into product_variants (id, product_id, size_label, price, currency, stock_quantity, low_stock_threshold, subscription_eligible, sku) values ('1057ab6f-571f-41ac-9bc3-e8e34965915e', 'c0da4df3-7de8-4a85-84bd-aefb5a556fae', '100ml', 22000, 'NGN', 4, 10, false, 'SO-FRA-100');
insert into product_facets (product_id, facet_id) values ('c0da4df3-7de8-4a85-84bd-aefb5a556fae', 'a724c0df-a980-4506-b2d8-c323187cb673');
insert into product_facets (product_id, facet_id) values ('c0da4df3-7de8-4a85-84bd-aefb5a556fae', '3701886b-55ac-4f55-824d-10a355c2189e');
insert into product_facets (product_id, facet_id) values ('c0da4df3-7de8-4a85-84bd-aefb5a556fae', 'f3d1200f-28a8-45f3-b3b6-8f00f8251bc7');
insert into product_facets (product_id, facet_id) values ('c0da4df3-7de8-4a85-84bd-aefb5a556fae', 'a1edd207-8462-4d84-ba2c-04e0458c9cb9');
insert into product_facets (product_id, facet_id) values ('c0da4df3-7de8-4a85-84bd-aefb5a556fae', '201b4c8f-0378-4a45-b5f8-6826c3b19ba0');

