import { randomUUID } from "node:crypto";
import { ALL_FACETS } from "@/lib/data/seed/facets";
import { SEED_PRODUCTS } from "@/lib/data/seed/products";

function str(value: string | null | undefined): string {
  if (value === null || value === undefined) return "null";
  return `'${value.replace(/'/g, "''")}'`;
}

function bool(value: boolean): string {
  return value ? "true" : "false";
}

const lines: string[] = [];
lines.push("-- Generated by scripts/generate-seed-sql.ts from lib/data/seed/*.ts — do not hand-edit.");
lines.push("-- Re-run: npx tsx scripts/generate-seed-sql.ts > supabase/seed.sql");
lines.push("");
lines.push("truncate table product_facets, product_images, product_variants, products, facets restart identity cascade;");
lines.push("");

const facetIdBySlug = new Map<string, string>();
lines.push("-- Facets (type / origin / use_case)");
for (const facet of ALL_FACETS) {
  const id = randomUUID();
  facetIdBySlug.set(facet.slug, id);
  lines.push(
    `insert into facets (id, facet_type, label, slug) values ('${id}', ${str(facet.facetType)}, ${str(facet.label)}, ${str(facet.slug)});`
  );
}
lines.push("");

for (const product of SEED_PRODUCTS) {
  const productId = randomUUID();
  lines.push(`-- ${product.name}`);
  lines.push(
    `insert into products (id, name, slug, description, status, is_pet_safe, pet_safe_note) values ('${productId}', ${str(product.name)}, ${str(product.slug)}, ${str(product.description)}, ${str(product.status)}, ${bool(product.isPetSafe)}, ${str(product.petSafeNote)});`
  );

  for (const variant of product.variants) {
    lines.push(
      `insert into product_variants (id, product_id, size_label, price, currency, stock_quantity, low_stock_threshold, subscription_eligible, sku) values ('${randomUUID()}', '${productId}', ${str(variant.sizeLabel)}, ${variant.price}, ${str(variant.currency)}, ${variant.stockQuantity}, ${variant.lowStockThreshold}, false, ${str(variant.sku)});`
    );
  }

  product.images.forEach((image, index) => {
    if (image.isPlaceholder) return; // no storage_path yet — PDP falls back to the labeled placeholder
    lines.push(
      `insert into product_images (id, product_id, storage_path, alt_text, sort_order) values ('${randomUUID()}', '${productId}', ${str(image.src)}, ${str(image.alt)}, ${index});`
    );
  });

  for (const facet of product.facets) {
    const facetId = facetIdBySlug.get(facet.slug);
    if (!facetId) throw new Error(`Unknown facet slug: ${facet.slug}`);
    lines.push(`insert into product_facets (product_id, facet_id) values ('${productId}', '${facetId}');`);
  }
  lines.push("");
}

console.log(lines.join("\n"));
